# Site settings 
title: "Home- Rohit Sarang"
description: "My CV!!"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Rohit Sarang"
resume_title:                   "Budding Chief Magic Officer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hello@rohitsarang.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 97111 94611"
resume_contact_address:         "Dwarka, New Delhi"

resume_header_contact_info:     "Dwarka, New Delhi, India • +91 97111-94611 • hello@rohitsarang.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi there! I am Rohit, and engineer turned payments professional. I am working with HDFC Bank as a Product Manager creating innovative payment solution. I love playing with technology, building tools and have interest in finance. Hit me at <b>hello@rohitsarang.com</b> to know more. Lets meet over a coffee and explore!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/rohit200abc"
  resume_linkedin_url:          "https://www.linkedin.com/in/rohitsarang"
  resume_instagram_url:         "https://www.instagram.com/thecruelcritic/"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
